[workspace]
members = [
    "zingo-nymwalletd",
    "zingo-nymserverd",
    "zingo-proxyd",
    "zingo-rpc",
]

# Use the edition 2021 dependency resolver in the workspace, to match the crates
resolver = "2"
