[package]
name = "zaino-testutils"
version = "0.1.1"
description = "Crate containing Zaino test specific functionality."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
# Used by zcash-local-net:
test_fixtures = []

[dependencies]
zaino-fetch = { path = "../zaino-fetch" }
zainod = { path = "../zainod" }

# ZingoLib
zingolib = { workspace = true }

# Miscellaneous Workspace
tokio = { workspace = true }
tonic = { workspace = true }
http = { workspace = true }

# Miscellaneous Crate
ctrlc = { workspace = true }
tempfile = { workspace = true }
portpicker = { workspace = true }
