[package]
name = "integration-tests"
version = "0.1.1"
description = "Crate containing Zaino 'Wallet-to-Node' tests."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
# Test utility
zaino-testutils = { path = "../zaino-testutils" }

# Test fixtures
zcash_local_net = { git = "https://github.com/zingolabs/zcash-local-net.git", branch = "dev", features = [ "test_fixtures" ] }

# Lightclient
zingolib = { workspace = true }

# Runtime
tokio = { workspace = true }

# Logging
tracing-subscriber = "0.3.15"

# Lazy
once_cell = "1.20.2"
