[package]
name = "zingo-rpc"
version = "0.1.0"
authors = ["zingo@zingolabs.org"]
edition = "2021"

[features]
# NOTE: Deprecated
nym_poc = []

[dependencies]
zcash_client_backend = { workspace = true, features = ["lightwalletd-tonic"] }
zingo-netutils = { workspace = true }

nym-sdk = { workspace = true }
nym-sphinx-addressing = { workspace = true }
nym-validator-client = { workspace = true }
nym-bin-common = { workspace = true }
nym-sphinx-anonymous-replies = { workspace = true }

http = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
http-body = { workspace = true }

